Azure/azure-libraries-for-net

Tests/Fluent.Tests/TestAzureCredentialsFactory.cs
src/ResourceManagement/Graph.RBAC/CertificateCredentialImpl.cs
src/ResourceManagement/Graph.RBAC/PasswordCredentialImpl.cs
src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs
src/ResourceManagement/ResourceManager/Authentication/AzureCredentialsFactory.cs
src/ResourceManagement/ResourceManager/AzureEnvironment.cs
src/ResourceManagement/ResourceManager/Core/RestClient/RestClient.cs

Fix for https://github.com/Azure/azure-libraries-for-net/issues/33

Fixed German and USGov RDFE endpoints.

---

src/ResourceManagement/ServiceBus/Domain/IAuthorizationKeys.cs
src/ResourceManagement/ServiceBus/Domain/IAuthorizationRule.cs
src/ResourceManagement/ServiceBus/Domain/IAuthorizationRules.cs
src/ResourceManagement/ServiceBus/Domain/ICheckNameAvailabilityResult.cs
src/ResourceManagement/ServiceBus/Domain/INamespaceAuthorizationRule.cs
src/ResourceManagement/ServiceBus/Domain/INamespaceAuthorizationRules.cs
src/ResourceManagement/ServiceBus/Domain/IQueue.cs
src/ResourceManagement/ServiceBus/Domain/IQueueAuthorizationRule.cs
src/ResourceManagement/ServiceBus/Domain/IQueueAuthorizationRules.cs
src/ResourceManagement/ServiceBus/Domain/IQueues.cs
src/ResourceManagement/ServiceBus/Domain/IServiceBusNamespace.cs
src/ResourceManagement/ServiceBus/Domain/IServiceBusNamespaces.cs
src/ResourceManagement/ServiceBus/Domain/ISubscription.cs
src/ResourceManagement/ServiceBus/Domain/ISubscriptions.cs
src/ResourceManagement/ServiceBus/Domain/ITopic.cs
src/ResourceManagement/ServiceBus/Domain/ITopicAuthorizationRule.cs
src/ResourceManagement/ServiceBus/Domain/ITopicAuthorizationRules.cs
src/ResourceManagement/ServiceBus/Domain/ITopics.cs
src/ResourceManagement/ServiceBus/Domain/TopicAuthorizationRule/Definition/IDefinition.cs
src/ResourceManagement/ServiceBus/Domain/TopicAuthorizationRule/Update/IUpdate.cs

Changes corresponding to Java SDK commit https://github.com/Azure/azure-sdk-for-java/pull/1948/commits/d56299efff43f731f02f9c9f009cb9f8c5ccf82e

GA of ServiceBus API

---

Tests/Fluent.Tests/ResourceManager/ResourceGroupsTests.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ResourceManager.ResourceGroups/CanCRUDResourceGroup.json
src/ResourceManagement/ResourceManager/Core/ResourceUtils.cs

String value should be single quoted.
Otherwise for '.ListByTag("a","b")', it will report
```
Unhandled Exception: Microsoft.Rest.Azure.CloudException: Invalid $filter 'tagname eq a and tagvalue eq b' specified in the query string.
```
I can get expected result with '.ListByTag("'a'","'b'")

Fix odata query for tags

---

src/ResourceManagement/Graph.RBAC/ActiveDirectoryApplicationsImpl.cs

Fix for issue https://github.com/Azure/azure-libraries-for-net/issues/40

Fixed BadRequest exception for ActiveDirectoryApplications.GetByName method

---

src/ResourceManagement/ResourceManager/Region.cs

(and deprecating an old typo constant...)

New Azure gov regions

---

src/ResourceManagement/ResourceManager/Authentication/AzureCredentialsFactory.cs

Fix for https://github.com/Azure/azure-libraries-for-net/issues/124

Adding more help content for FromUser method in AzureCredentials Factory

---

Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ResourceManager.Deployment/CanCancelVirtualNetworkDeployment.json
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ResourceManager.Deployment/CanUpdateVirtualNetworkDeployment.json
src/ResourceManagement/ResourceManager/Deployment/DeploymentImpl.cs

Create the resource group if it does not exist on BeginCreate().

---

Tests/Fluent.Tests/ContainerService/KubernetesClustersTest.cs

Work around to automatically pass valid creds required when creating the kubernetes cluster.

AKS - fix for KubernetesClusterCRUDTest live test 

---

src/ResourceManagement/Monitor/ActivityLogsImpl.cs

Java fix for Azure/azure-libraries-for-net#178

Monitor Activity log response filter fix

---

src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs

Fixes Azure/azure-sdk-for-net#4090

Fix MSI token audiences with trailing slash

---

Tests/Fluent.Tests/BatchAI/BatchAITests.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.BatchAI/CanCreateJob.json
Tests/Samples.Tests/BatchAI.cs
src/ResourceManagement/BatchAI/BatchAIJobImpl.cs

fix for https://github.com/Azure/azure-libraries-for-net/issues/170

Fixing BatchAIJob refresh functionality

---

Tests/Fluent.Tests/ServiceBus/ServiceBusTests.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ServiceBus/CanCreateNamespaceThenCRUDOnQueue.json
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ServiceBus/CanCreateNamespaceThenCRUDOnTopic.json
src/ResourceManagement/ServiceBus/Generated/QueuesOperations.cs
src/ResourceManagement/ServiceBus/Generated/TopicsOperations.cs

Removing client side constraint on service-bus queue and topic name max size

---

src/ResourceManagement/ContainerInstance/ContainerImpl.cs
src/ResourceManagement/ContainerInstance/Domain/ContainerGroup/Definition/IDefinition.cs
src/ResourceManagement/ContainerInstance/Domain/InterfaceImpl/ContainerImpl.cs

This PR addresses the issue in https://github.com/Azure/azure-libraries-for-net/issues/216.

ACI: Fix for UDP external and internal ports

---

src/ResourceManagement/BatchAI/BatchAIJobImpl.cs

Addressing code review for PR #226.

adding cancellation token to async method call in BatchAI

---

src/ResourceManagement/Sql/Generated/FirewallRulesOperations.cs

Work around for SQL Firewall Rule service returning XML response rather than expected JSON.

SQL fix for Firewall Rule

---

src/ResourceManagement/Network/Generated/Models/FrontendIPConfigurationInner.cs
src/ResourceManagement/Network/Generated/Models/NetworkInterfaceIPConfigurationInner.cs
src/ResourceManagement/Network/Generated/Models/NetworkInterfaceInner.cs
src/ResourceManagement/Network/Generated/Models/SubnetInner.cs
src/ResourceManagement/Network/Generated/Models/VirtualNetworkGatewayConnectionInner.cs
src/ResourceManagement/Network/LoadBalancerFrontendImpl.cs
src/ResourceManagement/Network/NetworkInterfaceImpl.cs
src/ResourceManagement/Network/NicIPConfigurationImpl.cs
src/ResourceManagement/Network/SubnetImpl.cs
src/ResourceManagement/Network/VirtualNetworkGatewayConnectionImpl.cs

Changing fields of Inners back to SubResource

 Changing fields of Inners back to SubResource

---

src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs

fix for https://github.com/Azure/azure-libraries-for-net/issues/284

fix for "Custom token credentials unsupported for Graph APIs"

---

src/ResourceManagement/Graph.RBAC/Domain/IRoleDefinitions.cs
src/ResourceManagement/Graph.RBAC/Domain/InterfaceImpl/RoleDefinitionsImpl.cs

Fix for https://github.com/Azure/azure-libraries-for-net/issues/245

Fixed IRoleDefinitions interface ListByScopeAsync method return type.

---

src/ResourceManagement/ResourceManager/Core/GroupableResources.cs
src/ResourceManagement/ResourceManager/IndependentChildrenImpl.cs
src/ResourceManagement/Sql/RecommendedElasticPoolImpl.cs
src/ResourceManagement/Sql/SqlDatabaseImpl.cs
src/ResourceManagement/Sql/SqlDatabaseOperationsImpl.cs
src/ResourceManagement/Sql/SqlElasticPoolOperationsImpl.cs
src/ResourceManagement/Sql/SqlFirewallRuleOperationsImpl.cs
src/ResourceManagement/Sql/SqlServerImpl.cs
src/ResourceManagement/Sql/SqlVirtualNetworkRuleOperationsImpl.cs

Fix for https://github.com/Azure/azure-libraries-for-net/issues/233

Fix for potential nullref exception in exception handling.

---

Tests/Fluent.Tests/ResourceManager/AzureEnvironmentTests.cs
src/ResourceManagement/ResourceManager/AzureEnvironment.cs

Support parsing AzureEnvironment by name

---

src/ResourceManagement/Storage/Domain/InterfaceImpl/StorageAccountImpl.cs
src/ResourceManagement/Storage/Domain/StorageAccount/Update/IUpdate.cs

fix for https://github.com/Azure/azure-libraries-for-net/issues/316

Fixed Storage method declaration

---

src/ResourceManagement/Network/ApplicationGatewayImpl.cs

When the size of an Application Gateway is being set the tier can be extracted and set.

ApplicationGateway: Extract and set the tier when the size is being set.

---

src/ResourceManagement/Azure.Fluent/Azure.cs
src/ResourceManagement/ResourceManager/Core/RestClient/RestClient.cs

fix for https://github.com/Azure/azure-libraries-for-net/issues/379

Exposed underlying management clients from rollup client.

---

src/ResourceManagement/ResourceManager/AzureEnvironment.cs

Fix the US AzureEnvironment auth endpoint

---

src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs

fix for https://github.com/Azure/azure-libraries-for-net/issues/326

Added better error messages for invalid ServicePrincipalLoginInformation object

---

Tests/Fluent.Tests/ResourceManager/DeploymentTests.cs
src/ResourceManagement/ResourceManager/Deployment/DeploymentImpl.cs

fix for https://github.com/Azure/azure-libraries-for-net/issues/122

Fixed beginCreate bug for Deployment

---

Tests/Fluent.Tests/SessionRecords/Fluent.Tests.TrafficManager/CanCreateUpdateTrafficManagerProfile.json
Tests/Fluent.Tests/TrafficManager/TrafficManagerTests.cs
src/ResourceManagement/TrafficManager/TrafficManagerProfileImpl.cs

Fix for https://github.com/Azure/azure-libraries-for-net/issues/121

Fixed TrafficManagerProfile Endpoints update bug

---

src/ResourceManagement/Graph.RBAC/ActiveDirectoryGroupImpl.cs

Fix for https://github.com/Azure/azure-libraries-for-net/issues/351

Fixed JsonSerializationException for ListMember on AD Group

---

Tests/Fluent.Tests/SessionRecords/Fluent.Tests.WebApp.WebApps/WebAppWithoutPhp.json
Tests/Fluent.Tests/WebApp/WebAppsTests.cs
src/ResourceManagement/AppService/WebAppBaseImpl.cs

Fix for https://github.com/Azure/azure-libraries-for-net/issues/392

Fixed invalid phpVersion error when creating web app

---

Tests/Fluent.Tests/GraphRbac/ApplicationsTests.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.Graph.RBAC.Applications/CanCRUDApplication.json
src/ResourceManagement/Graph.RBAC/ActiveDirectoryApplicationImpl.cs

Fix password credential on applications

---

Samples/Sql/ManageSqlServerKeysWithAzureKeyVaultKey.cs
Samples/Sql/ManageSqlVirtualNetworkRules.cs
Tests/Fluent.Tests/Common/TestTemplate.cs
Tests/Fluent.Tests/Network/NSGTests.cs
src/ResourceManagement/ResourceManager/Region.cs

Fix for https://github.com/Azure/azure-libraries-for-net/issues/432

Added AustraliaCentral and AustraliaCentral2 regions.

---

README.md

Fixed typo in doc

---

README.md

Fix for https://github.com/Azure/azure-libraries-for-net/issues/465

Fixed Java typo in the README.md.

---

src/ResourceManagement/TrafficManager/Domain/InterfaceImpl/TrafficManagerProfileImpl.cs
src/ResourceManagement/TrafficManager/Domain/TrafficManagerProfile/Definition/IDefinition.cs
src/ResourceManagement/TrafficManager/Domain/TrafficManagerProfile/Update/IUpdate.cs
src/ResourceManagement/TrafficManager/TrafficManagerProfileImpl.cs
src/ResourceManagement/TrafficManager/TrafficRoutingMethod.cs

Issue https://github.com/Azure/azure-libraries-for-net/issues/476
Adding support for Multivalue IP feature

Support ATM MultiValue IP feature

---

src/ResourceManagement/Graph.RBAC/ServicePrincipalImpl.cs

fix for  https://github.com/Azure/azure-libraries-for-net/issues/497

Fixed Application name during SP definition.

---

Tests/Fluent.Tests/TrafficManager/TrafficManagerTests.cs
src/ResourceManagement/TrafficManager/Domain/ITrafficManagerEndpoint.cs
src/ResourceManagement/TrafficManager/Domain/InterfaceImpl/TrafficManagerEndpointImpl.cs
src/ResourceManagement/TrafficManager/Domain/InterfaceImpl/TrafficManagerExternalEndpointImpl.cs
src/ResourceManagement/TrafficManager/TrafficManagerEndpointImpl.cs

Added test for multivalue IP, subnet routing, and custom header feature.

Added test for multivalue IP, subnet routing, and custom header feature.

---

Tests/Fluent.Tests/Locks/Locks.cs
src/ResourceManagement/Locks/ManagementLockImpl.cs

Fix for https://github.com/Azure/azure-libraries-for-net/issues/524

Fixed ResourceGroup management lock definition flow.

---

src/ResourceManagement/RedisCache/Domain/IRedisCache.cs
src/ResourceManagement/RedisCache/Domain/IRedisCacheBeta.cs
src/ResourceManagement/RedisCache/Domain/IRedisCachePremium.cs
src/ResourceManagement/RedisCache/Domain/IRedisCachePremiumBeta.cs
src/ResourceManagement/RedisCache/Domain/InterfaceImpl/RedisCacheImpl.cs
src/ResourceManagement/RedisCache/Domain/RedisCache/Definition/IDefinition.cs

Fix for https://github.com/Azure/azure-libraries-for-net/issues/564

Moved Reboot and Scheduled Updates functionality from Premium SKU to Base class.

---

src/ResourceManagement/Compute/DiskImpl.cs
src/ResourceManagement/Compute/Domain/IDisk.cs
src/ResourceManagement/Compute/Domain/InterfaceImpl/DiskImpl.cs

ref: https://github.com/Azure/azure-libraries-for-net/issues/565

Expose Disk.EncryptionSettings getter

---

Tests/Fluent.Tests/SessionRecords/Fluent.Tests.Sql/CanCRUDSqlDatabaseWithElasticPool.json
Tests/Fluent.Tests/Sql/SqlTests.cs
src/ResourceManagement/Sql/Domain/ISqlDatabase.cs
src/ResourceManagement/Sql/Domain/InterfaceImpl/SqlDatabaseImpl.cs
src/ResourceManagement/Sql/SqlDatabaseImpl.cs

https://github.com/Azure/azure-libraries-for-net/issues/563

Added Tags property for SQL Database.

---

Samples/Samples.csproj
Tests/AzSdk.test.reference.props
Tests/Fluent.Tests/CosmosDB/CosmosDBTest.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.CosmosDB/CosmosDBBugfix.json
src/AzSdk.reference.props
src/ResourceManagement/AppService/WebAppBaseImpl.cs
src/ResourceManagement/AppService/WebAppDiagnosticLogsImpl.cs
src/ResourceManagement/AppService/WebAppSourceControlImpl.cs
src/ResourceManagement/CosmosDB/CosmosDBAccountImpl.cs
src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.ResourceManager.Fluent.csproj

Fixed https://github.com/Azure/azure-libraries-for-net/issues/514
and https://github.com/Azure/azure-libraries-for-net/issues/562

Release 1.19 bugfixes

---

Tests/Fluent.Tests/SessionRecords/Fluent.Tests.WebApp.WarDeploy/CanDeployWar.json
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.WebApp.WarDeploy/CanDeployWarOnJava11.json
Tests/Fluent.Tests/WebApp/WarDeployTests.cs
src/ResourceManagement/AppService/JavaVersion.cs
src/ResourceManagement/AppService/RuntimeStack.cs
src/ResourceManagement/AppService/WebContainer.cs

Fix for issue #597, Add support for Java 11 in webapp

---

Tests/Fluent.Tests/Compute/VirtualMachineScaleSetTests.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.Compute.VirtualMachine.ScaleSet/CanGetSingleVMSSInstance.json
src/ResourceManagement/Compute/Domain/IVirtualMachineScaleSetVMsBeta.cs
src/ResourceManagement/Compute/VirtualMachineScaleSetVMsImpl.cs

Adding API to get a single virtual machine scale set instance by Instance Id.

Adding GetInstance Api to VirtualMachineScaleSetVMs

---

src/ResourceManagement/Azure.Fluent/Azure.cs

Correct spelling

---

Tests/Fluent.Tests/SessionRecords/Fluent.Tests.Storage.StorageAccounts/CanCreateWithKindSkuAndUpdateAccessTier.json
Tests/Fluent.Tests/Storage/StorageAccountsTests.cs
src/ResourceManagement/Storage/Generated/Models/StorageAccountInner.cs

BUG FIX (Storage): fixed storage's tags issue

---

Directory.Build.props

Bump version for release v1.24.1

---

src/ResourceManagement/AppService/RuntimeStack.cs

Adds new versions of NodeJS, NETCORE, PHP, and Ruby which are currently available in Azure config lists

Update new versions of the stacks

---

.travis.yml

PR already have azure pipeline for windows and linux.
travis would upload docker image on master.

travis build only on master and not on PR

---

src/ResourceManagement/Network/NetworkSecurityRuleImpl.cs

fix: Network Security Rule Impl DestinationAddressPrefixes error

---

Tests/Fluent.Tests/ServiceBus/ServiceBusTests.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ServiceBus/CanPerformCRUDOnSubscriptions.json

see [#799 ](https://github.com/Azure/azure-libraries-for-net/issues/799)

ServiceBus: add tests for session enable/disable

---

Samples/Samples.csproj
Tests/AzSdk.test.reference.props
src/ResourceManagement/ContainerInstance/Microsoft.Azure.Management.ContainerInstance.Fluent.csproj
src/ResourceManagement/EventHub/Microsoft.Azure.Management.EventHub.Fluent.csproj
src/ResourceManagement/Sql/Microsoft.Azure.Management.Sql.Fluent.csproj

Fix: update WindowsAzure.Storage dependency to latest(9.3.3)

---

Tests/Fluent.Tests/CosmosDB/CosmosDBTest.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.CosmosDB/CanCreateCassandraCosmosDB.json
src/ResourceManagement/CosmosDB/CosmosDBAccountImpl.cs
src/ResourceManagement/CosmosDB/Domain/CosmosDBAccount/Definition/IDefinition.cs
src/ResourceManagement/CosmosDB/Domain/CosmosDBAccount/Update/IUpdate.cs
src/ResourceManagement/CosmosDB/Domain/ICosmosDBAccount.cs
src/ResourceManagement/CosmosDB/Domain/InterfaceImpl/CosmosDBAccountImpl.cs

https://github.com/Azure/azure-libraries-for-java/pull/845

Add cassandra connector

---

src/ResourceManagement/ResourceManager/Authentication/MSILoginException.cs
src/ResourceManagement/ResourceManager/Authentication/MSITokenProvider.cs

https://github.com/Azure/azure-libraries-for-net/issues/527

Fix method typo.

---

src/ResourceManagement/ResourceManager/Deployment/DeploymentImpl.cs

Fix deployment result.

---

src/ResourceManagement/AppService/WebAppBaseImpl.cs

fix retry count in git

---

Tests/Fluent.Tests/Compute/VirtualMachinesTests.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.Compute.VirtualMachine.VirtualMachine/CanEncrypt.json
src/ResourceManagement/Compute/Domain/IVirtualMachineEncryption.cs
src/ResourceManagement/Compute/Domain/InterfaceImpl/LinuxDiskVolumeLegacyEncryptionMonitorImpl.cs
src/ResourceManagement/Compute/Domain/InterfaceImpl/LinuxDiskVolumeNoAADEncryptionMonitorImpl.cs
src/ResourceManagement/Compute/Domain/InterfaceImpl/WindowsVolumeLegacyEncryptionMonitorImpl.cs
src/ResourceManagement/Compute/Domain/InterfaceImpl/WindowsVolumeNoAADEncryptionMonitorImpl.cs
src/ResourceManagement/Compute/EncryptionExtensionIdentifier.cs
src/ResourceManagement/Compute/EncryptionSettings.cs
src/ResourceManagement/Compute/LinuxDiskVolumeLegacyEncryptionMonitorImpl.cs
src/ResourceManagement/Compute/LinuxDiskVolumeNoAADEncryptionMonitorImpl.cs
src/ResourceManagement/Compute/LinuxEncryptionExtensionUtil.cs
src/ResourceManagement/Compute/LinuxVMDiskEncryptionConfiguration.cs
src/ResourceManagement/Compute/VirtualMachineEncryptionConfiguration.cs
src/ResourceManagement/Compute/VirtualMachineEncryptionHelper.cs
src/ResourceManagement/Compute/VirtualMachineEncryptionImpl.cs
src/ResourceManagement/Compute/WindowsVMDiskEncryptionConfiguration.cs
src/ResourceManagement/Compute/WindowsVolumeLegacyEncryptionMonitorImpl.cs
src/ResourceManagement/Compute/WindowsVolumeNoAADEncryptionMonitorImpl.cs

https://github.com/Azure/azure-libraries-for-java/pull/782
https://github.com/Azure/azure-libraries-for-net/issues/737

feat: add No AAD Encryption Support

---

src/ResourceManagement/AppService/FunctionAppImpl.cs

test pass with both httpsOnly=true and httpsOnly=false

use kudu https endpoint

---

src/ResourceManagement/ResourceManager/Region.cs

https://github.com/Azure/azure-libraries-for-net/issues/856

middle east and africa region

---

src/ResourceManagement/ResourceManager/Authentication/AzureCredentialsFactory.cs
src/ResourceManagement/ResourceManager/Authentication/MSILoginInformation.cs

feat: add more options to create MSI Login Credentials

---

src/ResourceManagement/ContainerInstance/Generated/Models/ContainerGroupIpAddressType.cs
src/ResourceManagement/ContainerInstance/Generated/Models/ContainerGroupRestartPolicy.cs
src/ResourceManagement/ContainerInstance/Generated/Models/GpuSku.cs
src/ResourceManagement/ContainerInstance/Generated/Models/LogAnalyticsLogType.cs
src/ResourceManagement/ContainerInstance/Generated/Models/OperatingSystemTypes.cs
src/ResourceManagement/ContainerInstance/OSTypeName.cs

fix https://github.com/Azure/azure-libraries-for-net/issues/848

fix: Container Instance Generated error, without JsonConverter for ExpandableStringEnum

---

src/ResourceManagement/Compute/AvailabilitySetImpl.cs
src/ResourceManagement/Compute/VirtualMachineImpl.cs
src/ResourceManagement/Compute/VirtualMachineScaleSetImpl.cs

https://github.com/Azure/azure-libraries-for-net/issues/892

fix: return null when proximity placement group is null

---

Tests/Fluent.Tests/SessionRecords/Fluent.Tests.TrafficManager/CanCreateUpdateTrafficManagerProfile.json
Tests/Fluent.Tests/TrafficManager/TrafficManagerTests.cs
src/ResourceManagement/TrafficManager/Domain/ITrafficManagerProfile.cs
src/ResourceManagement/TrafficManager/Domain/InterfaceImpl/TrafficManagerProfileImpl.cs
src/ResourceManagement/TrafficManager/Domain/TrafficManagerProfile/Definition/IDefinition.cs
src/ResourceManagement/TrafficManager/Domain/TrafficManagerProfile/Update/IUpdate.cs
src/ResourceManagement/TrafficManager/TrafficManagerProfileImpl.cs

https://github.com/Azure/azure-libraries-for-net/issues/518

support fast failover setting to traffic manager

---

Tests/Fluent.Tests/GraphRbac/ApplicationsTests.cs
Tests/Fluent.Tests/GraphRbac/ServicePrincipalsTests.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.Graph.RBAC.Applications/CanCRUDApplication.json
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.Graph.RBAC.ServicePrincipals/CanCRUDServicePrincipal.json
src/ResourceManagement/Graph.RBAC/ActiveDirectoryApplicationImpl.cs
src/ResourceManagement/Graph.RBAC/CertificateCredentialImpl.cs
src/ResourceManagement/Graph.RBAC/Domain/ActiveDirectoryApplication/Definition/IDefinition.cs
src/ResourceManagement/Graph.RBAC/Domain/ActiveDirectoryApplication/Update/IUpdate.cs
src/ResourceManagement/Graph.RBAC/Domain/ICertificateCredential.cs
src/ResourceManagement/Graph.RBAC/Domain/InterfaceImpl/ActiveDirectoryApplicationImpl.cs
src/ResourceManagement/Graph.RBAC/Domain/InterfaceImpl/CertificateCredentialImpl.cs
src/ResourceManagement/Graph.RBAC/Domain/InterfaceImpl/ServicePrincipalImpl.cs
src/ResourceManagement/Graph.RBAC/Domain/ServicePrincipal/Definition/IDefinition.cs
src/ResourceManagement/Graph.RBAC/Domain/ServicePrincipal/Update/IUpdate.cs
src/ResourceManagement/Graph.RBAC/PasswordCredentialImpl.cs
src/ResourceManagement/Graph.RBAC/ServicePrincipalImpl.cs

fix https://github.com/Azure/azure-libraries-for-net/issues/915

Graph RBAC: add thumbprint in certificate definition

---

Tests/Fluent.Tests/SessionRecords/Fluent.Tests.WebApp.WebApps/CanCRUDWebApp.json
Tests/Fluent.Tests/WebApp/WebAppsTests.cs
src/ResourceManagement/AppService/Domain/InterfaceImpl/WebAppImpl.cs
src/ResourceManagement/AppService/Domain/WebApp/Definition/IDefinition.cs
src/ResourceManagement/AppService/Domain/WebApp/Update/IUpdate.cs
src/ResourceManagement/AppService/WebAppBaseImpl.cs
src/ResourceManagement/AppService/WebAppImpl.cs
src/ResourceManagement/AppService/WebAppRuntimeStack.cs

Fix https://github.com/Azure/azure-libraries-for-net/issues/935

support change runtime stack for web app on windows OS

---

src/ResourceManagement/AppService/HostNameSslBindingImpl.cs

fix: list certificate in whole subscription instead of one resource group

---

Tests/Fluent.Tests/Network/LoadBalancerTests.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.Network.LoadBalancer/CanCRUDOutboundRule.json
src/ResourceManagement/Network/Domain/ILoadBalancer.cs
src/ResourceManagement/Network/Domain/ILoadBalancerOutboundRule.cs
src/ResourceManagement/Network/Domain/ILoadBalancingRule.cs
src/ResourceManagement/Network/Domain/InterfaceImpl/LoadBalancerImpl.cs
src/ResourceManagement/Network/Domain/InterfaceImpl/LoadBalancerOutboundRuleImpl.cs
src/ResourceManagement/Network/Domain/InterfaceImpl/LoadBalancingRuleImpl.cs
src/ResourceManagement/Network/Domain/LoadBalancer/Definition/IDefinition.cs
src/ResourceManagement/Network/Domain/LoadBalancer/Update/IUpdate.cs
src/ResourceManagement/Network/Domain/LoadBalancerOutboundRule/Definition/IDefinition.cs
src/ResourceManagement/Network/Domain/LoadBalancerOutboundRule/Update/IUpdate.cs
src/ResourceManagement/Network/Domain/LoadBalancerOutboundRule/UpdateDefinition/IUpdateDefinition.cs
src/ResourceManagement/Network/Domain/LoadBalancingRule/Definition/IDefinition.cs
src/ResourceManagement/Network/Domain/LoadBalancingRule/Update/IUpdate.cs
src/ResourceManagement/Network/Domain/LoadBalancingRule/UpdateDefinition/IUpdateDefinition.cs
src/ResourceManagement/Network/LoadBalancerImpl.cs
src/ResourceManagement/Network/LoadBalancingRuleImpl.cs

Fix https://github.com/Azure/azure-libraries-for-net/issues/750

feature support load balancer outbound rule

---

Tests/Fluent.Tests/CosmosDB/CosmosDBTest.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.CosmosDB/CanCRUDSqlContainer.json
src/ResourceManagement/CosmosDB/CosmosDBAccountImpl.cs
src/ResourceManagement/CosmosDB/Domain/CosmosDBAccount/Definition/IDefinition.cs
src/ResourceManagement/CosmosDB/Domain/CosmosDBAccount/Update/IUpdate.cs
src/ResourceManagement/CosmosDB/Domain/ICosmosDBAccount.cs
src/ResourceManagement/CosmosDB/Domain/InterfaceImpl/CosmosDBAccountImpl.cs

close https://github.com/Azure/azure-libraries-for-net/issues/979
The interface name doesn't need to change.

Cosmos: add Automatic Failover Enable

---

Tests/Fluent.Tests/CosmosDB/CosmosDBTest.cs
src/ResourceManagement/CosmosDB/CassandraKeyspaceImpl.cs
src/ResourceManagement/CosmosDB/CassandraTableImpl.cs
src/ResourceManagement/CosmosDB/CosmosDBAccountImpl.cs
src/ResourceManagement/CosmosDB/Domain/CosmosDBAccount/Definition/IDefinition.cs
src/ResourceManagement/CosmosDB/Domain/CosmosDBAccount/Update/IUpdate.cs
src/ResourceManagement/CosmosDB/Domain/IndexingPolicy/Definition/IDefinition.cs
src/ResourceManagement/CosmosDB/Domain/IndexingPolicy/Update/IUpdate.cs
src/ResourceManagement/CosmosDB/Domain/InterfaceImpl/CosmosDBAccountImpl.cs
src/ResourceManagement/CosmosDB/Domain/InterfaceImpl/IndexingPolicyImpl.cs
src/ResourceManagement/CosmosDB/GremlinDatabaseImpl.cs
src/ResourceManagement/CosmosDB/GremlinGraphImpl.cs
src/ResourceManagement/CosmosDB/IndexingPolicyImpl.cs
src/ResourceManagement/CosmosDB/MongoCollectionImpl.cs
src/ResourceManagement/CosmosDB/MongoDBImpl.cs
src/ResourceManagement/CosmosDB/SqlContainerImpl.cs
src/ResourceManagement/CosmosDB/SqlDatabaseImpl.cs
src/ResourceManagement/CosmosDB/TableImpl.cs

fix comments https://github.com/Azure/azure-libraries-for-net/pull/994#pullrequestreview-369297306

Minor fix for cosmos db according to comments

---

.github/CODEOWNERS
Samples/samples.json

Change sample owner.

---

src/ResourceManagement/ContainerService/KubernetesClusterImpl.cs
src/ResourceManagement/ContainerService/KubernetesClustersImpl.cs

Deprecate GetAccessProfile api

---

src/ResourceManagement/AppService/Domain/IWebAppBase.cs
src/ResourceManagement/AppService/WebAppBaseImpl.cs

To be able to review/report the security setting of app services, we'd like to be able to access the MinTlsVersion.

adding MinTlsVersion

---

README.md

The ms doc seems lost to newer sdk.

add logging doc to readme

---

src/ResourceManagement/ResourceManager/Core/RestClient/ProviderRegistrationDelegatingHandler.cs

Fix incorrect exception discovered from https://github.com/Azure/azure-libraries-for-net/issues/1049

ignore error in ProviderRegistrationDelegatingHandler

---

Tests/Fluent.Tests/Compute/SharedGalleryImageTests.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.Compute.SharedGalleryImage/CanCreateUpdateGetDeleteGalleryImageVersion.json
src/ResourceManagement/Compute/Generated/Models/GalleryArtifactVersionSource.cs

Fix: [Azure/azure-sdk-for-net#10011](https://github.com/Azure/azure-sdk-for-net/issues/10011)
Refer: [swagger changes](https://github.com/Azure/azure-rest-api-specs/pull/9257)

Compute: remove ID as required in GalleryArtifactVersionSource

---

src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs
src/ResourceManagement/ResourceManager/Authentication/AzureCredentialsFactory.cs
src/ResourceManagement/ResourceManager/Authentication/ServicePrincipalLoginInformation.cs

There is signing problem in CertificateAuthenticationProvider. Fix first inside our project, and I'll open a PR at the azure-sdk-for-net
fix #615, fix #1014

Add certificate roll over

---

src/ResourceManagement/ResourceManager/Domain/IResourceGroups.cs

Change User to Use

---

src/ResourceManagement/Azure.Fluent/Azure.cs
src/ResourceManagement/Network/AzureFirewallImpl.cs

Fix https://github.com/Azure/azure-libraries-for-net/issues/1091 as well.

fix natRule bug

---

src/ResourceManagement/AppService/WebAppDiagnosticLogsImpl.cs

fix https://github.com/Azure/azure-libraries-for-net/issues/947

fix ApplicationLogging

---

src/ResourceManagement/AppService/FunctionAppImpl.cs
src/ResourceManagement/AppService/WebAppBaseImpl.cs

fix https://github.com/Azure/azure-libraries-for-net/issues/1105
only add setting if not provided by user

fix setting overwritten by function app redeployment

---

src/ResourceManagement/AppService/AppServiceBaseImpl.cs
src/ResourceManagement/AppService/AppServicePlanImpl.cs
src/ResourceManagement/AppService/Domain/AppServicePlan/Definition/IDefinition.cs
src/ResourceManagement/AppService/Domain/InterfaceImpl/AppServicePlanImpl.cs
src/ResourceManagement/AppService/PricingTier.cs

Add methods to specify consumption pricing tier

---

src/ResourceManagement/Azure.Fluent/Azure.cs

fix https://github.com/Azure/azure-libraries-for-net/issues/1101

allow PastDue in subscription

---

src/ResourceManagement/AppService/DeploymentSlotsImpl.cs
src/ResourceManagement/AppService/FunctionAppsImpl.cs
src/ResourceManagement/AppService/FunctionDeploymentSlotsImpl.cs
src/ResourceManagement/AppService/WebAppsImpl.cs

fix https://github.com/Azure/azure-libraries-for-net/issues/1132

NPE in appservice

---

src/ResourceManagement/Compute/Domain/IVirtualMachineImages.cs
src/ResourceManagement/Compute/GalleryImageImpl.cs
src/ResourceManagement/Compute/GalleryImageVersionImpl.cs
src/ResourceManagement/Compute/VirtualMachineImagesImpl.cs
src/ResourceManagement/ResourceManager/Core/ResourceUtils.cs
src/ResourceManagement/Storage/BlobContainerImpl.cs
src/ResourceManagement/Storage/BlobContainersImpl.cs
src/ResourceManagement/Storage/BlobServicePropertiesImpl.cs
src/ResourceManagement/Storage/ImmutabilityPolicyImpl.cs

fix https://github.com/Azure/azure-libraries-for-net/issues/1133

compute vm image GetById

---

src/ResourceManagement/Network/Domain/InterfaceImpl/SubnetImpl.cs
src/ResourceManagement/Network/Domain/Subnet/Definition/IDefinition.cs
src/ResourceManagement/Network/Domain/Subnet/Update/IUpdate.cs
src/ResourceManagement/Network/Domain/Subnet/UpdateDefinition/IUpdateDefinition.cs
src/ResourceManagement/Network/SubnetImpl.cs

fix https://github.com/Azure/azure-libraries-for-net/issues/738

support subnet delegations

---

src/ResourceManagement/KeyVault/Domain/ISecret.cs
src/ResourceManagement/KeyVault/Domain/InterfaceImpl/SecretImpl.cs

KeyVault: fix secret ListVersionsAsync

---

src/ResourceManagement/Graph.RBAC/ActiveDirectoryApplicationsImpl.cs
src/ResourceManagement/Graph.RBAC/ActiveDirectoryGroupsImpl.cs
src/ResourceManagement/Graph.RBAC/ActiveDirectoryUsersImpl.cs
src/ResourceManagement/Graph.RBAC/RoleDefinitionsImpl.cs
src/ResourceManagement/Graph.RBAC/ServicePrincipalsImpl.cs

GraphRbac: fix odata query filter with special characters

---

src/ResourceManagement/Cdn/CdnProfileImpl.cs
src/ResourceManagement/Cdn/Domain/CdnProfile/Definition/IDefinition.cs
src/ResourceManagement/Cdn/Domain/InterfaceImpl/CdnProfileImpl.cs

I added the required implementation to fix the bug 1162 reported [here](https://github.com/Azure/azure-libraries-for-net/issues/1162). Please review and confirm it works as expected.

Added Microsoft Standard SKU to the CDN Fluent Definition

---

Samples/Samples.csproj
src/AzSdk.reference.props
src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.ResourceManager.Fluent.csproj

upgrade clientruntime authentication version

---

src/ResourceManagement/TrafficManager/TrafficManagerEndpointImpl.cs

fix https://github.com/Azure/azure-libraries-for-net/issues/1187

traffic manager, remove duplicate key on customer headers

---

src/ResourceManagement/KeyVault/Domain/InterfaceImpl/VaultImpl.cs
src/ResourceManagement/KeyVault/Domain/Vault/Definition/IDefinition.cs
src/ResourceManagement/KeyVault/Domain/Vault/Update/IUpdate.cs
src/ResourceManagement/KeyVault/VaultImpl.cs

KeyVault: support soft delete for the key vault

---

src/ResourceManagement/AppService/Generated/Models/IpFilterTag.cs
src/ResourceManagement/AppService/Generated/Models/IpSecurityRestriction.cs

fix https://github.com/Azure/azure-libraries-for-net/issues/1189

use IpFilterTag from api-version 2020-06

---

src/ResourceManagement/Storage/Generated/Models/SkuName.cs

To align: #901 
The storage service is not allowed to create using `Standard_RAGZRS` while it will return this if the storage account is created by other tools with newer API version.

Storage: manual revert on SkuName

---

.github/CODEOWNERS
src/ResourceManagement/AppService/FunctionAppImpl.cs

Fix https://github.com/Azure/azure-libraries-for-net/issues/1214
Also fix the missing `EndpointSuffix`, it affects non-global Azure.

bug fix on function app, elastic premium plan need WEBSITE_* settings

---

src/ResourceManagement/Compute/VirtualMachineCustomImageImpl.cs
src/ResourceManagement/Compute/VirtualMachineCustomImagesImpl.cs

Fix https://github.com/Azure/azure-libraries-for-net/issues/1223

Fix GetById bug, init of HyperV should be in define flow, not in get flow

---

src/ResourceManagement/AppService/FunctionAppImpl.cs

Fix https://github.com/Azure/azure-libraries-for-net/issues/1224

update functionapp master key api to use host/default/listkeys

---

src/ResourceManagement/ResourceManager/Deployment/DeploymentImpl.cs

Fix https://github.com/Azure/azure-libraries-for-net/issues/822

bug fix, SetInner in async method

---

src/ResourceManagement/ResourceManager/Authentication/AzureCredentialsFactory.cs

fixed typos

---

src/ResourceManagement/ResourceManager/Region.cs

The [westus3 region is now live](https://azure.microsoft.com/en-us/blog/expanding-cloud-services-microsoft-launches-its-sustainable-datacenter-region-in-arizona/). Adding it to the region list.

Adding westus3 region

---

src/ResourceManagement/AppService/Domain/InterfaceImpl/WebAppAuthenticationImpl.cs
src/ResourceManagement/AppService/Domain/WebAppAuthentication/Definition/IDefinition.cs
src/ResourceManagement/AppService/Domain/WebAppAuthentication/UpdateDefinition/IUpdateDefinition.cs
src/ResourceManagement/AppService/WebAppAuthenticationImpl.cs
src/ResourceManagement/Compute/VirtualMachineImpl.cs
src/ResourceManagement/Network/AzureFirewallImpl.cs
src/ResourceManagement/Network/Domain/IHasNetworkInterfaces.cs

fix https://github.com/Azure/azure-libraries-for-net/issues/1247
fix https://github.com/Azure/azure-libraries-for-net/issues/1248
fix https://github.com/Azure/azure-libraries-for-net/issues/1241
fix https://github.com/Azure/azure-libraries-for-net/issues/1238

fix NPE on azure firewall, and other bug fixes

---

src/ResourceManagement/ContainerInstance/ContainerGroupImpl.cs

Fix https://github.com/Azure/azure-libraries-for-net/issues/1275
Tested but not added to case. One can refer to Java test https://github.com/Azure/azure-sdk-for-java/pull/24418

fix no ports in container group

---

src/ResourceManagement/ResourceManager/Region.cs

Adds the missing region support for SwedenCentral

Support Region.SwedenCentral

---

.github/CODEOWNERS
Tests/Fluent.Tests/Network/PrivateLinkServiceTests.cs
Tests/Fluent.Tests/SessionRecords/Fluent.Tests.Network.PrivateLinkService/CanCreateUpdate.json
src/ResourceManagement/Network/PrivateLinkServiceImpl.cs

response of the loadbalancer frontend in private link service only contains id.

network, bug fix on private link service

---

src/ResourceManagement/AppService/PublishingProfileImpl.cs

fix https://github.com/Azure/azure-libraries-for-net/issues/1300

bug fix, ftps is not supported in profile

---

src/ResourceManagement/AppService/WebAppMsiHandler.cs

fix https://github.com/Azure/azure-libraries-for-net/issues/1317

web, bug fix on msi handler

---

README.md

fix https://github.com/Azure/azure-libraries-for-net/issues/1330
nuget package is marked as deprecated, e.g. https://www.nuget.org/packages/Microsoft.Azure.Management.Compute.Fluent/

update readme for depecate message
