Azure/azure-libraries-for-net

Tests/Fluent.Tests/Batch/BatchTests.cs, Tests/Fluent.Tests/Compute/VirtualMachineAvailabilityZoneOperationsTests.cs, Tests/Fluent.Tests/Compute/VirtualMachineExtensionImageTests.cs, Tests/Fluent.Tests/Compute/VirtualMachineExtensionTests.cs, Tests/Fluent.Tests/Compute/VirtualMachineManagedDiskOperationsTests.cs, Tests/Fluent.Tests/Compute/VirtualMachineScaleSetManagedDiskOperationsTests.cs, Tests/Fluent.Tests/Compute/VirtualMachinesTests.cs, Tests/Fluent.Tests/KeyVault/KeyVaultTests.cs, Tests/Fluent.Tests/Miscellaneous/RestClientTests.cs, Tests/Fluent.Tests/Network/ApplicationGateway/PrivateComplex.cs, Tests/Fluent.Tests/Network/PublicIpAddressTests.cs, Tests/Fluent.Tests/Redis/RedisCacheTests.cs, Tests/Fluent.Tests/ServiceBus/ServiceBusTests.cs, Tests/Fluent.Tests/Sql/SqlTests.cs, src/ResourceManagement/Compute/ContainerServiceAgentPoolImpl.cs, src/ResourceManagement/Network/Domain/InterfaceImpl/LocalNetworkGatewayImpl.cs, src/ResourceManagement/Network/Domain/InterfaceImpl/VirtualNetworkGatewayImpl.cs, src/ResourceManagement/Network/Domain/LocalNetworkGateway/Definition/IDefinition.cs, src/ResourceManagement/Network/Domain/LocalNetworkGateway/Update/IUpdate.cs, src/ResourceManagement/Network/Domain/VirtualNetworkGateway/Definition/IDefinition.cs, src/ResourceManagement/Network/Domain/VirtualNetworkGateway/Update/IUpdate.cs, src/ResourceManagement/Network/LocalNetworkGatewayImpl.cs, src/ResourceManagement/Network/VirtualNetworkGatewayConnectionImpl.cs, src/ResourceManagement/Network/VirtualNetworkGatewayImpl.cs, src/ResourceManagement/ServiceBus/QueueImpl.cs
- Cleanup of miscellaneous compiler warnings
- Documentation fixes in networking
compat breaks from previous beta:
- DisableBgp() renamed as WithoutBgp() in fluent update flows for virtual and local network gateways
=> Miscellanous cleanups

src/ResourceManagement/gulpfile.js
This PR makes it so the `@preview` version of autorest.csharp is used by default. We tend to depend on more recently added generator features, and since so many people depend on the C# generator, it's hard to publish the generator as quickly as we want to make changes.
This also fixes the `--autorest-csharp` parameter so you can pass an NPM version number starting with an `@` symbol as the argument.
=> Gulp preview generator

src/ResourceManagement/Network/PublicIPAddressImpl.cs
fix for https://github.com/Azure/azure-libraries-for-net/issues/132
=> Fixed NullReferenceException in PublicIPAddressImpl.WithLeafDomainLabel

src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs, src/ResourceManagement/ResourceManager/Authentication/MSILoginInformation.cs, src/ResourceManagement/ResourceManager/Authentication/MSITokenProvider.cs
Current MSITokenProvider supports only System Assigned MSI, updating provider to support User Assigned Identity MSI as well
=> Enable User Assigned Identity in MSITokenProvider

Samples/Compute/ListComputeSkus.cs, Samples/Storage/ManageStorageAccountNetworkRules.cs, Tests/Samples.Tests/Compute.cs, Tests/Samples.Tests/SessionRecords/Samples.Tests.Storage/ManageManageStorageAccountNetworkRulesTest.json, Tests/Samples.Tests/Storage.cs, src/ResourceManagement/Compute/ComputeSkuImpl.cs, src/ResourceManagement/Compute/Generated/Models/StorageAccountTypes.cs
Adding `StandardSSD_LRS` enum value to `StorageAccountTypes` in this [commit](https://github.com/Azure/azure-libraries-for-net/commit/a59c1b979e4e827572729647b51238f3832ffd40). Opened an [issue](https://github.com/Azure/azure-rest-api-specs/issues/2343)  in rest api spec. For now this need to be manually patched otherwise deserialization of the values *will fail* and clients will start seeing exceptions.
=> [Fix]: Adding StorageAccountTypes::StandardSSD_LRS, [Samples]: Storage network rules & compute SKU

src/ResourceManagement/Compute/Generated/Models/StorageAccountTypes.cs
Related to the issue described in this [PR](https://github.com/Azure/azure-libraries-for-net/pull/144)
While testing with different subscriptions, found that there is one more enum value `Standard_ZRS`, this PR add that value as well. Update the [issue](https://github.com/Azure/azure-rest-api-specs/issues/2343) in the api spec.
=> Adding StorageAccountTypes::Standard_ZRS

src/ResourceManagement/gulpfile.js
Fixes issues in .NET code generation noted by @milismsft.
At some point a new generator was published which adds the `/Generated` path component for us, so we need to stop adding it ourselves, and the README.md we are consuming from azure-rest-api-specs is starting to contain `clear-output-folder: true`, which we don't want because we have our own method of clearing out generated files in gulpfile.js.
=> Gulpfile fixes

src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs
Without this the token sent to the graph endpoint doesn't work on .net standard.
Looks like an oversight in the code. See issue here:
https://github.com/Azure/azure-libraries-for-net/issues/104
=> Fixed issue where netstandard doesn't get the correct token for the graph endpoint

src/ResourceManagement/Compute/ComputeManager.cs, src/ResourceManagement/Graph.RBAC/CertificateCredentialImpl.cs, src/ResourceManagement/Graph.RBAC/GraphRBACManager.cs, src/ResourceManagement/Graph.RBAC/PasswordCredentialImpl.cs, src/ResourceManagement/Msi/MsiManager.cs, src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs, src/ResourceManagement/ResourceManager/Core/RestClient/RestClient.cs
A number of the managers downcast the `RestClient`'s `Credentials` to `AzureCredentials` (eg https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Compute/ComputeManager.cs#L46).  Combined with the public facing side of the API accepting `ServiceClientCredentials` as input, we end up with an unfortunate violation of Liskov Substitution Principal that means code like this doesn't work;
```
// using Microsoft.Azure.Services.AppAuthentication(Prerelease)
var azureServiceTokenProvider = new AzureServiceTokenProvider();
var token = await azureServiceTokenProvider.GetAccessTokenAsync("https://management.core.windows.net/");
var tenantId = azureServiceTokenProvider.PrincipalUsed.TenantId;
var client = RestClient
.Configure() …
```
=> Support custom\external ServiceClientCredentials

Tests/Fluent.Tests/Network/ApplicationGateway/PrivateMinimal.cs, src/ResourceManagement/Network/Domain/ApplicationGatewaySslCertificate/UpdateDefinition/IUpdateDefinition.cs, src/ResourceManagement/Network/Domain/InterfaceImpl/ApplicationGatewaySslCertificateImpl.cs
Prior to this PR, IBlank<ParentT> interface in IUpdateDefinition.cs wasn't correctly implemented; so we had no way of adding data to an SSL certificate in the Application gateway's update stage.
See #257
=> Add support for reading SSL certificate from Pfx file during Application gateway update stage

Tests/Fluent.Tests/GraphRbac/ApplicationsTests.cs, Tests/Fluent.Tests/GraphRbac/ServicePrincipalsTests.cs, Tests/Fluent.Tests/SessionRecords/Fluent.Tests.Graph.RBAC.Applications/CanCRUDApplication.json, Tests/Fluent.Tests/SessionRecords/Fluent.Tests.Graph.RBAC.ServicePrincipals/CanCRUDServicePrincipal.json, src/ResourceManagement/Graph.RBAC/ActiveDirectoryApplicationImpl.cs, src/ResourceManagement/Graph.RBAC/Domain/IActiveDirectoryApplication.cs, src/ResourceManagement/Graph.RBAC/Domain/IServicePrincipal.cs, src/ResourceManagement/Graph.RBAC/ServicePrincipalImpl.cs
Fixing issue #356  Get service principal fails when service principal has multiple keys with the same name
Note: this is a breaking change as getters for credentials previously returned Dictionary indexed by name and now return Dictionary indexed by id.
=> Fixing operations with ActiveDirectoryApplication with multiple credentials with same name

src/ResourceManagement/AppService/KuduCredentials.cs
We ran into an issue where the payload of the JWT couldn't be parsed correctly, this turned out to be because it needed to be padded, this fix should work, but may be better to look into the use of a jwt parsing library.
=> JWT payload not padded in FunctionCredentials

src/ResourceManagement/ServiceBus/Generated/SubscriptionsOperations.cs
it was already removed in a previous PR for topic and queueoperations
- see https://github.com/Azure/azure-libraries-for-net/pull/188
but not from SubscriptionsOperations
this PR removes this limit as well
=> Remove topicName max length validation in  SubscriptionsOperations

src/ResourceManagement/Network/PublicIPAddressImpl.cs
fix for https://github.com/Azure/azure-libraries-for-net/issues/434
=> Update PublicIpAddress's dnsName throw NullReferenceException

src/ResourceManagement/Azure.Fluent/Azure.cs
Currently, using `IAuthenticated.WithDefaultSubscription()` makes a blocking API call.
This PR adds an asynchronous version of the method so that the consumer doesn't need to block their current thread.  
Sample usage:
```cs
AzureCredentials creds = new AzureCredentialsFactory().FromServicePrincipal(
_azureConfig.ServicePrincipalUsername, _azureConfig.ServicePrincipalPassword, _azureConfig.Tenant,
AzureEnvironment.AzureGlobalCloud);
IAzure azure = await Microsoft.Azure.Management.Fluent.Azure.Authenticate(creds)
.WithDefaultSubscriptionAsync();
```
=> Add IAuthenticated.WithDefaultSubscriptionAsync() method

src/ResourceManagement/Compute/VirtualMachineScaleSetVMImpl.cs
False for this field throws exceptions, null was tested to work. This addresses [issue #663](https://github.com/Azure/azure-libraries-for-net/issues/663).
=> Change tempDisk value on VirtualMachineScaleSetVM Reimage to null from false

src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs, src/ResourceManagement/ResourceManager/Authentication/AzureCredentialsFactory.cs
=> Add constructor taking tenant id as parameter for AzureCredentials constructor when using MSI

src/ResourceManagement/ResourceManager/Authentication/MSITokenProvider.cs
The `.AppService` codepaths in `MSITokenProvider` did not support user-assigned MSIs, only system-assigned MSIs (while the `.VirtualMachine` paths support both).  This change refactors `MSITokenProvider` slightly to leverage the logic the `.VirtualMachine` path is already using in the `.AppService` path as well.
Fixes #734
=> Add support for user-assigned MSIs from AppServices to MSITokenProvider

Samples/Samples.csproj, Tests/AzSdk.test.reference.props, src/AzSdk.reference.props, src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.ResourceManager.Fluent.csproj
updated clientruntime.azure.auth to 2.4.0, which require clientruntime 2.3.19 hence also upgraded
=> updated clientruntime.azure.auth to 2.4.0

Tests/Fluent.Tests/ManagementClientTest.cs, src/ResourceManagement/CosmosDB/Generated/CosmosDB.cs
In short, the root cause is that manager.Inner.BaseUri = https://management.azure.com/ (which should not even be there) is hiding the real one (manager.Inner as FluentServiceClientBase<CosmosDB>).BaseUri = https://management.usgovcloudapi.net/
=> fix cosmosdb

src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs
Since the AzureCredentials object may be accessed by different threads it must be a ConcurrentDictionary or be protected by synchronization primitives.
=> Use concurrent dictionary for accessing the credentials cache.

src/ResourceManagement/Graph.RBAC/ActiveDirectoryApplicationImpl.cs
WithoutReplyUrl must add existing Reply URLs before attempting to remove one (see WithReplyUrl in update mode for similar logic).
If not added, the updateParameters.ReplyUrls will be null and nothing will happen.
=> WithoutReplyUrl must add existing Reply URLs

src/ResourceManagement/Monitor/MetricAlertRuleTimeAggregation.cs
Service confirmed they actually missing this in swagger spec.
https://github.com/Azure/azure-libraries-for-net/issues/861
=> add Count to monitor time aggregate

Tests/Fluent.Tests/ResourceManager/GenericResourcesTests.cs, src/ResourceManagement/ResourceManager/GenericResource/GenericResourceImpl.cs
https://github.com/Azure/azure-libraries-for-net/issues/42
=> fix: parentResourceId could not be null

src/ResourceManagement/Compute/Domain/InterfaceImpl/VirtualMachineImpl.cs, src/ResourceManagement/Compute/Domain/VirtualMachine/Definition/IDefinition.cs, src/ResourceManagement/Compute/VirtualMachineImpl.cs
add WithVaultSecret to windows managed and unmanaged definitions. This is needed in order to use WithWinRM.
Fixes #660
=> Add vault secret support for windows machines

src/ResourceManagement/AppService/FunctionAppsImpl.cs, src/ResourceManagement/AppService/WebAppsImpl.cs
from sev3 ICM
fix https://github.com/Azure/azure-libraries-for-net/issues/992
=> proper filter for webapp and function app

Tests/Fluent.Tests/PagedCollectionTests.cs, src/ResourceManagement/ResourceManager/Core/PagedCollection.cs
Fix https://github.com/Azure/azure-libraries-for-net/issues/996
=> fix stalling on PagedCollection, when value is empty but nextLink is valid

Tests/Fluent.Tests/ResourceManager/GenericResourcesTests.cs, Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ResourceManager.GenericResources/CanCRUDWithProviderApiVersion.json, src/ResourceManagement/ResourceManager/GenericResource/GenericResourceImpl.cs, src/ResourceManagement/ResourceManager/GenericResource/GenericResourcesImpl.cs
=> Resources: support api version when listing generic resources

src/ResourceManagement/ResourceManager/Core/ExternalChildResourceCollection.cs
Fix #1002 
This was caused by the difference from dotnet frameworks when getting TaskCanceledException. For example, `netcoreapp2.0` will set task as `Faulted` while `net461` will set as `Canceled`.
=> Resources: support TaskCanceledException handling for different .NET environment

src/ResourceManagement/ContainerInstance/Domain/ContainerGroup/Definition/IDefinition.cs
Addresses feature request #1068 
Currently you cannot define a container instance via the .NET SDK that has both an empty directory defined and a volume mapping to Azure Files.
The issue is that as with the fluent API soon as I use WithEmptyDirectoryVolume , you cannot then use DefineVolume and visa versa.
This PR means that you can now do this
```
var containerGroup = azure.ContainerGroups.Define(cgName)
...
.WithPrivateImageRegistry(imageServer, imageUser, imagePassword)
.DefineVolume("existingvolume")
...
.Attach()
.WithEmptyDirectoryVolume("emptyvolume")
.DefineContainerInstance(cgName + "-1")
...
```
=> Define a container instance with both an empty directory defined and an existing volume 

Tests/Fluent.Tests/SessionRecords/Fluent.Tests.WebApp.WebApps/CanCRUDWebAppWithContainer.json, Tests/Fluent.Tests/WebApp/WebAppsTests.cs, src/ResourceManagement/AppService/Domain/InterfaceImpl/WebAppImpl.cs, src/ResourceManagement/AppService/Domain/WebApp/Definition/IDefinition.cs, src/ResourceManagement/AppService/PricingTier.cs, src/ResourceManagement/AppService/WebAppImpl.cs
fix https://github.com/Azure/azure-libraries-for-net/issues/1146
=> support webapp windows container

src/ResourceManagement/Network/AzureFirewallNatRuleCollectionImpl.cs
Fixed the get method to return the existing rules instead of an empty list
=> Fixed the get method of Rules in AzureFirewallNatRuleCollectionImpl

src/ResourceManagement/AppService/RuntimeStack.cs
Added .net core 3.1 to the runtime stack
=> Allow .net Core 3.1 to be specified in AppServices

src/ResourceManagement/AppService/HostNameBindingImpl.cs
I couldn't add hostname binding with wildcard subdomain though it can be done via azure portal. Tweaked regex expression a bit, so it could match wildcard
=> Fix regex to allow wildcard subdomain

Directory.Build.props
@weidongxu-microsoft @xccc-msft @yungezz It seems the AssemblyVersion will affect the DLL version, which causes that customer cannot auto-update their DLL. I'm not sure the problem details due to we do not use AssemblyFileVersion in the project. So I think the most convenient way is update it every time we release.
=> Release 1.36.1 due to assemblyFileVersion need update

src/ResourceManagement/AppService/FunctionAppImpl.cs
The `AutoSetAlwaysOn` and `IsConsumptionAppServicePlan` methods were implemented prior to the PremiumV2 and PremiumV3 app service plan tiers. Consequently, the condition based on string equality can no longer be met for modern premium tiers:
```csharp
public static readonly PricingTier PremiumP1v2 = new PricingTier("PremiumV2", "P1v2");
public static readonly PricingTier PremiumP2v2 = new PricingTier("PremiumV2", "P2v2");
public static readonly PricingTier PremiumP3v2 = new PricingTier("PremiumV2", "P3v2");
public static readonly PricingTier PremiumP1v3 = new PricingTier("PremiumV3", "P1v3");
public static readonly PricingTier PremiumP2v3 = new PricingTier("PremiumV3", "P2v3");
public static readonly PricingTier PremiumP3v3 = new PricingTier("PremiumV3", "P3v3");
```
This causes the …
=> Adjusted helper methods to the new Premium tier service app plans

Samples/Monitor/QueryMetricsAndActivityLogs.cs, Samples/Monitor/SecurityBreachOrRiskActivityLogAlerts.cs
Some of the samples for querying metrics will not work currently because date-conversion to universal time is missing. I fixed it by simply adding the conversion in those samples.
Fixes the reason #1232 originally was created by me.
=> Fixed missing universal conversion in samples.

src/ResourceManagement/Network/Generated/Models/ApplicationGatewayHttpListenerInner.cs
This fixes a bug with the ApplicationGatewayHttpListenerInner resulting in null hostnames when utilizing the multiple hostnames and/or wildcard hostnames feature in an HTTP Listener. 
Null hostnames results in the following error when applying any changes to an Application Gateway using this feature:
HostName must be specified if RequireServerNameIndication is true in Http Listener
StackTrace: ```Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: SetActiveDeploymentSlot
---> System.AggregateException: One or more errors occurred. (HostName must be specified if RequireServerNameIndication is true in Http Listener /subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Network/applicationGateways/REDACTED/httpListeners/REDACTED.)
---> …
```
=> Fix null hostnames in ApplicationGatewayHttpListener
